module Raw = struct
  let comment s = Format.asprintf "; %s" s

  let vendored_dirs glob = Format.asprintf "(vendored_dirs %s)" glob

  let duniverse_dune_content =
    [ comment "This file is generated by duniverse.";
      comment
        "Be aware that it is likely to be overwritten by your next duniverse pull invocation.";
      vendored_dirs "*"
    ]
end
